kind: pipeline
name: default
type: docker

trigger:
  branch:
  - main

steps:
- name: test and build
  image: golang
  environment:
    GOOS: windows
    GOARCH: amd64
  commands:
  - go test
  - go build -o winlogstream.exe
 
- name: scp files - build number
  image: appleboy/drone-scp
  settings:
    host: apps.carelinkdevelopment.com
    username: pavel.simsa
    password:
      from_secret: ssh_password
    port: 22
    target: /data/caddy/winlogstream/build_${DRONE_BUILD_NUMBER}
    source: winlogstream.exe
    
- name: scp files - latest
  image: appleboy/drone-scp
  settings:
    host: apps.carelinkdevelopment.com
    username: pavel.simsa
    password:
      from_secret: ssh_password
    port: 22
    target: /data/caddy/winlogstream/_latest
    source: winlogstream.exe
    
- name: scp files - readme
  image: appleboy/drone-scp
  settings:
    host: apps.carelinkdevelopment.com
    username: pavel.simsa
    password:
      from_secret: ssh_password
    port: 22
    target: /data/caddy/winlogstream
    source: README.md