name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOOS: windows
      GOARCH: amd64

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run:  go get ./...
      
    - name: Build
      run:  go build -v -o artifacts/ -ldflags "-X main.Version=1.0.${{ github.run_id }}"
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: ${{github.event_name}} == "push"
      with:
        name: winlogstream
        path: artifacts/winlogstream.exe
        retention-days: 5